### ISSUE TITLE
PC without Persistent Memory hardware

### ISSUE THREAD

**Issue by thuyngch** [baotonglu/apex#2]
Hi @baotonglu ,
Thanks for your great work.

I would like to run your code on a normal PC without Persistent Memory hardware.
How can I setup to run it?

Thank you!

**Comment by baotonglu** [comment]
Hi,

You could create a RAM Disk on your machine to use DRAM to simulate the PM (e.g., https://unix.stackexchange.com/questions/66329/creating-a-ram-disk-on-linux).  

Then you could directly replace the PM path in our code base with RAM Disk path to run it. 

Best regards,
Baotong

**Comment by thuyngch** [comment]
Thank you very much!
