### ISSUE TITLE
evaluation problems

### ISSUE THREAD

**Issue by JiahongJiahong** [baotonglu/apex#4]
<img width="681" alt="7bb77b60f21c033db320da29b60b5d8" src="https://user-images.githubusercontent.com/100759652/198863734-2fbeb2ed-c7bc-4c6a-aa69-6b9eb882c3f7.png">
When I try to evaluate APEX, this problem arises, how to solve it?

**Comment by baotonglu** [comment]
Sorry for the confusion. I have removed it.
