### ISSUE TITLE
some bugs with bulk_load function

### ISSUE THREAD

**Issue by Spear-Neil** [baotonglu/apex#5]
There may be some bugs with bulk_load function, when bulk_load size isn't very great (so the root node will be a leaf node at this time). 

```
int main(int argc, char** argv) {
  size_t bulk_cnt = std::stol(argv[1]);

  Tree<uint64_t, uint64_t>* index = generate_index<uint64_t, uint64_t>();
  auto values = new std::pair<uint64_t, uint64_t>[bulk_cnt];
  for(size_t i = 0; i < bulk_cnt; i++) {
    values[i].first = i;
    values[i].second = i;
  }

  index->bulk_load(values, bulk_cnt);

  for(size_t i = 0; i < bulk_cnt; i++) {
    size_t value;
    if(index->search(i, &value)) {
      if(value != i) std::cout << "Error find: " << i << value << std::endl;
    } else {
      std::cout << "Fail find: " << i << " " << value << std::endl;
    }
  }

  my_alloc::BasePMPool::ClosePool();
  return 0;
}
```

**Comment by sunce4t** [comment]
hi，Have you solved this problem? I also encountered the same problem. During the bulk_load process, a segfault occurred. After checking, I found that the segfault occurred in the delete_node function.
void bulk_load(const V values[], int num_keys) {
     if (stats_.num_keys > 0 || num_keys <= 0) {
       return;
     }
     delete_node(root_node_); // delete the empty root node from constructor(segment fault)
thx！
